version: 2
jobs:
  build:
    working_directory: ~/my_app
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          - RAILS_ENV=test
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_ROOT_HOST=%
    steps:
      - checkout

      # Restore bundle cache for gems, so we dont have to install them again if Gemfile.lock is the same
      - type: cache-restore
        key: my_app-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=2 --retry=3

      # Store bundle cache for gems
      - type: cache-save
        key: my_app-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec rake db:create db:schema:load

      - type: shell
        command: |
          bundle exec rspec --color \
                            --format documentation \
                            --require rails_helper \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml

      - type: store_artifacts
        path: /tmp/test-results

      - type: store_test_results
        path: /tmp/test-results

      - run: CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN bundle exec codeclimate-test-reporter
