default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  strict: false

development:
  <<: *default

test: &test
  <<: *default

production: &production
  <<: *default
